---
- name: Create ~/.bashrc.d directory
  file:
    path: '{{ user_home }}/.bashrc.d'
    state: directory

- name: Source files from ~/.bashrc.d
  blockinfile:
    path: '{{ user_home }}/.bashrc'
    marker: '# {mark} ANSIBLE MANAGED BLOCK .bashrc.d'
    block: |
      if [ -d ${HOME}/.bashrc.d ]
      then
        for file in ~/.bashrc.d/*.bashrc
        do
          source "${file}"
        done; unset file
      fi
