---
- name: Create ~/.ssh directory
  file:
    path: '{{ user_home }}/.ssh'
    state: directory
    mode: '0700'

- name: Install keychain
  apt: name=keychain state=present
  become: yes

- name: Set up keychain init
  copy:
    src: ssh/keychain.bashrc
    dest: '{{ user_home }}/.bashrc.d/99-keychain.bashrc'
