---
- name: Install venv
  ansible.builtin.apt:
    name: python3-venv
  become: true

- name: Install pipx
  ansible.builtin.command: python3 -m pip install --user pipx

- name: Install tmuxp
  ansible.builtin.command: python3 -m pipx install tmuxp
