---
- ansible.builtin.import_tasks:
    file: postgres.yml
  become: true

- ansible.builtin.import_tasks:
    file: redis.yml
  become: true

- ansible.builtin.import_tasks:
    file: dev_deps.yml
  become: true

- ansible.builtin.import_tasks:
    file: utilities.yml
  become: true

- ansible.builtin.import_tasks:
    file: aws.yml
